name: Test upload-tartifact

on:
  - push

jobs:
  test-upload-tartifact:
    runs-on: ubuntu-latest
    name: Test upload-tartifact GHA
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Initial Tartifact
        uses: alehechka/upload-tartifact@main
        with:
          name: test
          path: README.md

      - name: Second Tartifact (test cleanup of prior)
        uses: alehechka/upload-tartifact@main
        with:
          name: test2
          path: README.md
